package model

// Code generated by go-bridget/mig. DO NOT EDIT.

import (
	"time"
)

// MaillistGroup generated for db table `maillist_group`.
//
// This is the top level mail list group.
type MaillistGroup struct {
	// The ID assigned to the mail list
	ID string `db:"id"`

	// The name of the mail list
	Title string `db:"title"`

	// Created At Time
	CreatedAt *time.Time `db:"created_at"`
}

// GetID will return the value of ID.
func (m *MaillistGroup) GetID() string { return m.ID }

// GetTitle will return the value of Title.
func (m *MaillistGroup) GetTitle() string { return m.Title }

// GetCreatedAt will return the value of CreatedAt.
func (m *MaillistGroup) GetCreatedAt() *time.Time { return m.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (m *MaillistGroup) SetCreatedAt(stamp time.Time) { m.CreatedAt = &stamp }

// MaillistGroupTable is the name of the table in the DB.
const MaillistGroupTable = "`maillist_group`"

// MaillistGroupFields is a list of all columns in the DB table.
var MaillistGroupFields = []string{"id", "title", "created_at"}

// MaillistGroupPrimaryFields are the primary key fields in the DB table.
var MaillistGroupPrimaryFields = []string{"id"}
