---
version: "3"

# Setup GOTOOLCHAIN workaround for #75031:
# https://github.com/golang/go/issues/75031#issuecomment-3195256688

vars:
  goversion:
    sh: go env GOVERSION
  toolchain: '{{.goversion}}+auto'

tasks:
  default:
    desc: "Run platform base"
    env:
      PLATFORM_DB_DEFAULT: "mysql://platform:platform@tcp(127.0.0.1:3306)/platform"
      PLATFORM_DB_MAILLIST: "mysql://platform:platform@tcp(127.0.0.1:3306)/platform_maillist"
    cmds:
      - goimports -w .
      - gofumpt -w .
      - go run .

  bench:
    desc: "Run benchmarks"
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
    cmd: go test -bench=. -benchmem -cpu 1,2,4 -race -v ./...

  test:
    desc: "Run tests with escape analysis"
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
      CGO_ENABLED: 0
    cmd: go test -count=1 -v -cover -coverpkg=./... -coverprofile=pkg.cov ./...

  migrate:
    desc: "Run migrations"
    cmds:
      - mig lint --db-dsn="platform:platform@tcp(127.0.0.1:3306)/platform_maillist" --schema platform_maillist
      - mig docs --db-dsn="platform:platform@tcp(127.0.0.1:3306)/platform_maillist" --schema platform_maillist --output=./docs
      - mig gen --db-dsn="platform:platform@tcp(127.0.0.1:3306)/platform_maillist" --go.skip-json --schema platform_maillist --output=./model

  cover:
    desc: "Show source coverage"
    cmds:
      - defer: rm -f pkg.cov.json
      - go tool cover -func=pkg.cov | summary coverfunc --json > pkg.cov.json
      - go-fsck extract ./...
      - go-fsck coverage -c pkg.cov.json -o go-fsck.json
      - go-fsck coverage

  uncover:
    desc: "Show uncovered source"
    cmd: uncover pkg.cov

  setup:
    desc: "Install dev tooling"
    env:
      GOBIN: /usr/local/bin
    cmds:
      - go install github.com/gregoryv/uncover/...@latest
      - go install mvdan.cc/gofumpt@latest
